name: "left4casino"
services:
    bot:
        build:
            context: "."
            dockerfile: "Dockerfile"
        profiles:
            - "all"
        restart: "always"
        stop_signal: SIGINT
        volumes:
            # Path to .toml file with settings
            - "./settings.toml:/app/settings.toml"
            # Path to localization directory
            - "./bot/locale/example/en:/app/bot/locale/current/en"
        environment:
            - CONFIG_FILE_PATH=/app/settings.toml
        depends_on:
            - redis

    redis:
        profiles:
            - "all"
            - "infra"
        image: "redis:8-alpine"
        restart: "always"
        volumes:
            # Path to redis.conf file
            - "./redis.conf:/usr/local/etc/redis/redis.conf"
            # Redis volume
            - "redis_data:/data"
        command: "redis-server /usr/local/etc/redis/redis.conf"
        healthcheck:
            test: [ "CMD", "redis-cli","ping" ]

volumes:
    redis_data:
